CREATE TABLE olympics.medal (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  medal_name VARCHAR(50) DEFAULT NULL,
  CONSTRAINT pk_medal PRIMARY KEY (id)
);

CREATE TABLE olympics.noc_region (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  noc VARCHAR(5) DEFAULT NULL,
  region_name VARCHAR(200) DEFAULT NULL,
  CONSTRAINT pk_nocregion PRIMARY KEY (id)
);

CREATE TABLE olympics.sport (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  sport_name VARCHAR(200) DEFAULT NULL,
  PRIMARY KEY (id)
);



CREATE TABLE olympics.city (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  city_name VARCHAR(200) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE olympics.event (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  sport_id INT DEFAULT NULL,
  event_name VARCHAR(200) DEFAULT NULL,
  CONSTRAINT pk_event PRIMARY KEY (id),
  CONSTRAINT fk_ev_sp FOREIGN KEY (sport_id) REFERENCES olympics.sport (id)
);


CREATE TABLE olympics.games (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  games_year INT DEFAULT NULL,
  games_name VARCHAR(100) DEFAULT NULL,
  season VARCHAR(100) DEFAULT NULL,
  CONSTRAINT pk_games PRIMARY KEY (id)
);

CREATE TABLE olympics.games_city (
  games_id INT DEFAULT NULL,
  city_id INT DEFAULT NULL,
  CONSTRAINT fk_gci_city FOREIGN KEY (city_id) REFERENCES olympics.city (id),
  CONSTRAINT fk_gci_gam FOREIGN KEY (games_id) REFERENCES olympics.games (id)
);
CREATE TABLE olympics.person (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  full_name VARCHAR(500) DEFAULT NULL,
  gender VARCHAR(10) DEFAULT NULL,
  height INT DEFAULT NULL,
  weight INT DEFAULT NULL,
  CONSTRAINT pk_person PRIMARY KEY (id)
);


CREATE TABLE olympics.person_region (
  person_id INT DEFAULT NULL,
  region_id INT DEFAULT NULL,
  CONSTRAINT fk_per_per FOREIGN KEY (person_id) REFERENCES olympics.person (id),
  CONSTRAINT fk_per_reg FOREIGN KEY (region_id) REFERENCES olympics.noc_region (id)
);
CREATE TABLE olympics.games_competitor (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  games_id INT DEFAULT NULL,
  person_id INT DEFAULT NULL,
  age INT DEFAULT NULL,
  CONSTRAINT pk_gamescomp PRIMARY KEY (id),
  CONSTRAINT fk_gc_gam FOREIGN KEY (games_id) REFERENCES olympics.games (id),
  CONSTRAINT fk_gc_per FOREIGN KEY (person_id) REFERENCES olympics.person (id)
);
CREATE TABLE olympics.competitor_event (
  event_id INT DEFAULT NULL,
  competitor_id INT DEFAULT NULL,
  medal_id INT DEFAULT NULL,
  CONSTRAINT fk_ce_com FOREIGN KEY (competitor_id) REFERENCES olympics.games_competitor (id),
  CONSTRAINT fk_ce_ev FOREIGN KEY (event_id) REFERENCES olympics.event (id),
  CONSTRAINT fk_ce_med FOREIGN KEY (medal_id) REFERENCES olympics.medal (id)
);
